server:
  port: 8020
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: cyj-entity-creater
  thymeleaf:
    check-template: false
    check-template-location: false
logging:
  level:
    org.hibernate: INFO