server:
  port: 8020
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.2:8761/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: cyj-entity-creater
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: false
  devtools:
    restart:
      enabled: true
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.2:3306/entity_create?useSSL=false
    username: root
    password: 68762306
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG
Path:
  path: D:\OneDrive\cyj\cyj-entity-creater\src\main\java\com\example\cyjentitycreater\JavaBean\
  reference: com.example.cyjentitycreater.JavaBean