server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: cyj-sso
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    ds1:
      platform: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/data_page_menu?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: 68762306
    ds2:
      platform: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/data_user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: 68762306

