server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: cyj-api
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-wait: 100000
        max-idle: 10
        max-active: 100
    timeout: 5000
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data_user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 68762306
#feign的配置，连接超时及读取超时配置
feign:
  client:
    default-config: my-config
    config:
      my-config:
        connectTimeout: 6000000
        readTimeout: 6000000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false