server:
  port: 8000
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/noice?useSSL=false
    username: root
    password: 68762306
  application:
    name: cyj-user
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG
security:
  basic:
    enabled: true
    path: /admin
  user:
    name: noice
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://noice:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true