server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: cyj-log
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data_user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 68762306
feign:
  client:
    default-config: my-config
    config:
      my-config:
        connectTimeout: 6000000
        readTimeout: 6000000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
