spring:
  application:
    name: cyj-eureka
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    fetchRegistry: false
    registerWithEureka: false