spring:
  application:
    name: cyj-eureka
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: 123456
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
    fetchRegistry: false
    registerWithEureka: false