server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://192.168.1.4:8761/eureka/
security:
  basic:
    enabled: true
  user:
    name: noice
    password: 123
